### ISSUE TITLE
How to disable configuration and generating output in console log

### ISSUE THREAD

**Issue by Alexml8456** [azachar/protractor-screenshoter-plugin#10]
Hello.
Please help me to disable console log output that generated by "protractor-screenshoter-plugin".
Output looks like this:

`Activated Protractor Screenshoter Plugin, ver. 0.2.3 (c) 2016 [object Object] and contributors`
`The resolved configuration is:`
`{ screenshotPath: 'target/e2e',`
  `clearFoldersBeforeTest: true,`
  `withLogs: 'false',`
  `screenshotOnExpect: 'failure',`
  `screenshotOnSpec: 'failure',`
  `htmlReport: 'true',`
  `writeReportFreq: 'asap',`
  `package: 'protractor-screenshoter-plugin' }`
`Creating reporter at target/e2e/`
`done`
`Generating target/e2e/report.js`
`Generating target/e2e/report.js`
`Generating target/e2e/report.js`

I don't know how to disable this output.
Also I don't know why for one test case, generated 3 similar strings in console log:
`Generating target/e2e/report.js`
`Generating target/e2e/report.js`
`Generating target/e2e/report.js`

**Comment by azachar** [comment]
Hello,

there is no such a configuration option yet, such a PR would be very welcome :)

Cheers,
Andrej

**Comment by azachar** [comment]
As per your second question, there are 3 same logs generated because of asynchronicity of taking logs and screenshots. It is not clear when it is done, even if your spec is already finished, postprocessing your screenshot might take some time. The final report needs to be updated everytime log or screenshot postprocessing is done.

 If you want you can adjust frequency of writing report by using option `writeReportFreq: 'end'` or `writeReportFreq: 'spec'`

Hope it helped you a bit.

**Comment by azachar** [comment]
Actually, you can use this branch https://github.com/azachar/protractor-screenshoter-plugin/tree/feat-ascii-image, which has that log disabled.

**Comment by Alexml8456** [comment]
Thank you for feedback, it's works!
