### ISSUE TITLE
[Question]- Is there any way to name the screenshots which are generated in screenshots folder

### ISSUE THREAD

**Issue by nimishseraphim** [azachar/protractor-screenshoter-plugin#31]
As of now in the screenshots folder we have <randomName.png>.
Is there any way I can name the screenshots properly?

**Comment by azachar** [comment]
Hello, 
It does not make any sense doing so. This was explained since the beginning of this fork in the readme file. On the top of that file names are limited in their size, which brings another pile of issues in terms of portability. 

Could you explain me your motivation behind? 

There is a reporter that you should alway use with it. You should never rely on raw data.

Cheers,
Andrej
