### ISSUE TITLE
Browser name

### ISSUE THREAD

**Issue by RatkoR** [azachar/protractor-screenshoter-plugin#39]
How can I see what browser was used per screenshot?

We have a bunch of different browsers and it always prints "default" above screenshot. Like it is in your screenshot examples. Is there a way to put browser info there? Like "Chrome - Linux" like it is specified in protractor's capabilities.

**Comment by gtroshinnc** [comment]
@RatkoR 
In TypeScript:

you can declarate custom names of your browser instanses by global screenshotBrowsers varible
```
const forkedBrowser = browser.forkNewDriverInstance()

beforeAll(() => {
    global['screenshotBrowsers'] = {}
    global['screenshotBrowsers']['defaultBrowser'] = browser // it is means default (main) browser
    global['screenshotBrowsers']['forkedBrowser'] = forkedBrowser
  })
```

In JavaScript, as described [in readme of this project.](https://github.com/azachar/protractor-screenshoter-plugin#multi-browser-chat-alike-app)

**Comment by kito99** [comment]
@gtroshinnc I don't see how that would work in a simple case where you have configured different browsers in protractor.conf.js. For example, we have chrome, firefox, and safari configured there, and are not using browser.forkNewDriverInstance(). All we need is for the report output to display the value of `capabilities.get('browserName')`.

**Comment by azachar** [comment]
Dear @kito99, 

Well, currently there is no support for that. Your PR would be more than welcome!

I guess, that it should be improved somewhere here

https://github.com/azachar/protractor-screenshoter-plugin/blob/a2c7e7adb6d9fce829a1117561547fef4c2f65b3/index.js#L146

Have a look at how to contribute. Also, please note that there is a dependent plugin, that needs to be updated in order to display your modifications if there is a change in data API.

Cheers,
Andrej
